openapi: 3.0.0
x-stoplight:
  id: ff85zzu171gza
info:
  title: Selfnet APP
  version: 1.0.0-alpha.2
servers:
  - url: 'http://localhost:3000'
paths:
  /invoices:
    get:
      summary: GET invoices
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-invoices
      parameters:
        - schema:
            type: string
            enum:
              - processing
              - historical
          in: query
          name: type
        - schema:
            type: string
          in: query
          name: start_range
          description: UNIX datetime. Used only if type == "processing".
        - schema:
            type: string
          in: query
          name: end_range
          description: UNIX datetme. Used only if type == "processing".
  /transactions:
    parameters: []
    get:
      summary: Get transactions
      tags: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    x-stoplight:
                      id: mu86ei9s8eig3
                    type: array
                    items:
                      $ref: '#/components/schemas/TransactionOutput'
      operationId: get-transactions
      description: Gets a list of the matching transactions
      parameters:
        - schema:
            type: integer
          in: query
          name: card_type
        - schema:
            type: integer
          in: query
          name: start_range
          description: UNIX datetime
        - schema:
            type: integer
          in: query
          name: end_range
          description: UNIX datetime
        - schema:
            type: string
            enum:
              - oil
              - nonoil
          in: query
          name: type
      requestBody:
        content: {}
components:
  schemas:
    Invoice:
      title: Invoice
      x-stoplight:
        id: mwp240vykhj95
      type: object
      properties:
        id:
          type: integer
          x-stoplight:
            id: 86ai4wd9he9k2
        supplier:
          type: object
          x-stoplight:
            id: xkbev68yk6pg9
          properties:
            name:
              type: string
              x-stoplight:
                id: tr1x62l374f0q
        fuel_station:
          type: object
          x-stoplight:
            id: h0zjb86pggzj6
          properties:
            name:
              type: string
              x-stoplight:
                id: ir6qfe8lb9k0x
        amount:
          type: number
          x-stoplight:
            id: mnn2j4xvpjvpx
        status:
          type: string
          x-stoplight:
            id: 0gilxih0xgf0x
        document_type:
          type: string
          x-stoplight:
            id: 6l3hvd416s4q9
        date:
          type: string
          x-stoplight:
            id: 8l8ek87r71z09
          format: date
        number:
          type: string
          x-stoplight:
            id: mgpuxsbo40ho7
    TransactionOutput:
      title: TransactionOutput
      x-stoplight:
        id: qxpfdaufrou29
      type: object
      properties:
        datetime:
          type: string
          x-stoplight:
            id: 2yf1t4uzchp4v
          format: date-time
        fuel_station:
          type: object
          x-stoplight:
            id: wtaduw2nz8whp
          properties:
            name:
              type: string
              x-stoplight:
                id: awhx7i604vlwi
        vehicle:
          type: object
          x-stoplight:
            id: og89xoevq96dz
          properties:
            plate:
              type: string
              x-stoplight:
                id: ettue6x5nprun
            km:
              type: integer
              x-stoplight:
                id: kbavtx3skr2qx
        article:
          type: object
          x-stoplight:
            id: yd7bdv7gjz13t
          properties:
            name:
              type: string
              x-stoplight:
                id: z78v6flckjuu1
            measure_unit:
              type: string
              x-stoplight:
                id: g1irmd0yfoa76
            quantity:
              type: number
              x-stoplight:
                id: 6dpd4nkaof6ej
        supply:
          type: object
          x-stoplight:
            id: bhvi6v0pog8jg
          properties:
            gross_amount:
              type: number
              x-stoplight:
                id: fc3vtwjuj9uqn
            net_amount:
              type: number
              x-stoplight:
                id: gsb7l3mvddnls
            gross_unit_price:
              type: number
              x-stoplight:
                id: s8nqrdsnk9dqx
            net_unit_price:
              type: number
              x-stoplight:
                id: 65bmppdc47ve1
        card:
          type: object
          x-stoplight:
            id: cwaflqdpho236
          properties:
            code:
              type: integer
              x-stoplight:
                id: d8tjwk4sdvh0z
            pan:
              type: string
              x-stoplight:
                id: 4v9o1rz1i8wue
            type:
              type: integer
              x-stoplight:
                id: vn2x2onbeaelg
            residue:
              type: number
              x-stoplight:
                id: 9tvb170jbvz3d
  securitySchemes:
    Cognito:
      type: oauth2
      flows:
        password:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
