name: API build and deploy

on:
  push:
    branches:
      - openapi-build

jobs:
  api-doc-deploy:
    name: build doc
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Generate new documentation
          uses: openapi-generators/openapitools-generator-action@v1
          with:
            generator: html2
            openapi-file: reference/Selfnet-APP.yaml
            command-args: -o docs
    
        - name: Commit new documentation
          run: |
            git config --global user.name 'ICAD Sistemi'
            git config --global user.email 'action@icadsistemi.com'
            git add docs/
            git commit -am "update docs"
            git push